class CreateResumePdfRequests < ActiveRecord::Migration[8.1]
  def change
    create_table :resume_pdf_requests do |t|
      t.references :resume, null: false, foreign_key: { on_delete: :cascade }

      # The id the browser already polls and downloads by. Generated by the
      # controller rather than the database so the status page can be rendered
      # in the same request that creates the row. Unique so a replayed enqueue
      # can never point two requests at one download.
      t.uuid :download_id, null: false

      # The pasted job description, encrypted at rest by Resume::PdfRequest --
      # that is the entire point of this table (issue #76, ADR-0022).
      t.text :text, null: false

      # created_at only: nothing ever updates a request. Indexed because
      # Resume::PdfRequest.purge_stale! scans on it every five minutes.
      t.datetime :created_at, null: false
    end

    add_index :resume_pdf_requests, :download_id, unique: true
    add_index :resume_pdf_requests, :created_at
  end
end
